# Generated by Django 3.2.4 on 2021-06-14 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('ein', models.CharField(max_length=25)),
                ('report_view', models.CharField(max_length=100, null=True)),
                ('order_schedule', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('in_inventory', models.IntegerField()),
                ('min_required', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRecPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_amount_to_order', models.IntegerField()),
                ('part_amount_ordered', models.IntegerField(null=True)),
                ('date_ordered', models.DateField(null=True)),
                ('received_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRecProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='parts')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='products')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('amount_used', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('name', 'website'), name='unique_vendor'),
        ),
        migrations.AddField(
            model_name='productpart',
            name='company_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockupapi.companypart'),
        ),
        migrations.AddField(
            model_name='productpart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockupapi.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockupapi.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='parts',
            field=models.ManyToManyField(related_name='products', through='stockupapi.ProductPart', to='stockupapi.CompanyPart'),
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockupapi.category'),
        ),
        migrations.AddField(
            model_name='part',
            name='unit_of_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockupapi.unitofmeasurement'),
        ),
        migrations.AddField(
            model_name='part',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockupapi.vendor'),
        ),
        migrations.AddField(
            model_name='orderrecproduct',
            name='order_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockupapi.orderrec'),
        ),
        migrations.AddField(
            model_name='orderrecproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockupapi.product'),
        ),
        migrations.AddField(
            model_name='orderrecpart',
            name='order_rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockupapi.orderrec'),
        ),
        migrations.AddField(
            model_name='orderrecpart',
            name='product_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockupapi.productpart'),
        ),
        migrations.AddField(
            model_name='orderrec',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockupapi.company'),
        ),
        migrations.AddField(
            model_name='orderrec',
            name='parts',
            field=models.ManyToManyField(through='stockupapi.OrderRecPart', to='stockupapi.ProductPart'),
        ),
        migrations.AddField(
            model_name='orderrec',
            name='products',
            field=models.ManyToManyField(related_name='order_recs', through='stockupapi.OrderRecProduct', to='stockupapi.Product'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockupapi.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companypart',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockupapi.company'),
        ),
        migrations.AddField(
            model_name='companypart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockupapi.part'),
        ),
        migrations.AddField(
            model_name='company',
            name='cat_pref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockupapi.category'),
        ),
        migrations.AddField(
            model_name='company',
            name='parts',
            field=models.ManyToManyField(related_name='companies', through='stockupapi.CompanyPart', to='stockupapi.Part'),
        ),
        migrations.AddField(
            model_name='company',
            name='vendor',
            field=models.ManyToManyField(related_name='companies', to='stockupapi.Vendor'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('name', 'part_number', 'vendor'), name='unique_part'),
        ),
    ]
