# Generated by Django 3.2.4 on 2021-07-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockupapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_rep_name', models.CharField(max_length=100)),
                ('sales_rep_phone', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=200)),
                ('login_username', models.CharField(max_length=100)),
                ('login_password', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockupapi.company')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockupapi.vendor')),
            ],
        ),
    ]
