# Generated by Django 3.2.4 on 2021-06-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
