# Generated by Django 3.2.4 on 2021-06-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrecpart',
            old_name='received_date',
            new_name='date_received',
        ),
    ]
