# Generated by Django 3.2.4 on 2021-07-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockupapi', '0002_companyvendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvendor',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyvendor',
            name='login_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyvendor',
            name='login_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyvendor',
            name='sales_rep_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyvendor',
            name='sales_rep_phone',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
