# Generated by Django 3.2.4 on 2021-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockupapi', '0002_rename_vendor_id_part_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='order_schedule',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='report_view',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
