# Generated by Django 3.2.4 on 2021-06-10 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockupapi', '0004_auto_20210609_1911'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('name', 'part_number', 'vendor'), name='unique_part'),
        )
    ]
