# Generated by Django 3.2.4 on 2021-06-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockupapi', '0004_auto_20210618_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
