# Generated by Django 3.2.4 on 2021-06-10 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockupapi', '0005_auto_20210610_0150'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('name', 'website'), name='unique_vendor'),
        )
    ]
