# Generated by Django 3.2.4 on 2021-06-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockupapi', '0006_auto_20210610_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypart',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        )
    ]
