# Generated by Django 3.2.4 on 2021-06-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockupapi', '0007_auto_20210610_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypart',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='companypart',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productpart',
            name='deleted',
            field=models.BooleanField(default=False),
        )
    ]
