# Generated by Django 3.2.4 on 2021-06-09 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('ein', models.CharField(max_length=25)),
                ('report_view', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=100, null=True)),
                ('order_schedule', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('bimonthly', 'Bimonthly'), ('quarterly', 'Quarterly')], max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('cat_pref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockup.category')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('in_inventory', models.IntegerField()),
                ('min_required', models.IntegerField()),
                ('cost', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockup.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockup.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockup.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('amount_used', models.IntegerField()),
                ('company_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockup.companypart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockup.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_number', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='parts')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockup.category')),
                ('unit_of_measurement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockup.unitofmeasurement')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockup.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRecProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sold', models.IntegerField()),
                ('order_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockup.orderrec')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockup.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRecPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_amount_to_order', models.IntegerField()),
                ('part_amount_ordered', models.IntegerField(null=True)),
                ('date_ordered', models.DateField(null=True)),
                ('received_date', models.DateField(null=True)),
                ('order_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockup.orderrec')),
                ('product_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockup.productpart')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockup.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='companypart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockup.part'),
        ),
    ]
